title: SecureTea
description: |
  THE OWASP SECURETEA PROJECT  
  IS AN APPLICATION DESIGNED TO  
  HELP SECURE A PERSONâ€™S LAPTOP
owner: OWASP 
first_published: 2019 
email: "your-email@domain.com"
baseurl: 
url: 

# https://securetea.org/
youtube: Fsx3H5g_tPQ
social:
  twitter: https://twitter.com/secureteatool
  github: https://github.com/OWASP/SecureTea-Project.git
  facebook-official: https://www.facebook.com/groups/owaspfoundation/
  youtube-square: https://www.youtube.com/channel/UCGdl9tpc1qZYcM3WRRFRPPA
  #email: /contact/
  #flickr:
  #instagram:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
plugins_dir: [jekyll-youtube]
